repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0 # Use the ref you want to point at
    hooks:
      - id: check-case-conflict
      - id: check-symlinks
      - id: destroyed-symlinks
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: mixed-line-ending
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: trailing-whitespace

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.2
    hooks:
      - id: prettier
        args: [--plugin, prettier-plugin-svelte, --write, .] # edit files in-place
        additional_dependencies:
          - prettier
          - prettier-plugin-svelte
          - svelte

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.48.0
    hooks:
      - id: eslint
        types: [file]
        args: [--fix, --resolve-plugins-relative-to, ~/.cache/pre-commit]
        files: \.(js|ts|svelte)$
        additional_dependencies:
          - eslint
          - typescript
          - svelte
          - svelte-eslint-parser
          - eslint-plugin-svelte
          - eslint-config-prettier
          - '@typescript-eslint/eslint-plugin'
          - '@typescript-eslint/parser'

ci:
  autofix_prs: true
  autofix_commit_msg: '[pre-commit.ci] Fixing issues with pre-commit'
  autoupdate_schedule: weekly
  autoupdate_commit_msg: '[pre-commit.ci] pre-commit automatically updated.'
  # skip: [] # Optionally list ids of hooks to skip on CI
